assistant_in_learning_new_words/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),

    path('users/', include("users.urls", namespace="users")),
    path('', include("words.urls", namespace="words")),
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (LogInView, SignUpView, UserUpdateView,
                    logout_and_redirect_to_login)

app_name = 'users'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup'),
    path("login/", LogInView.as_view(), name='login'),
    path("profile/<int:pk>", login_required(UserUpdateView.as_view()), name='profile'),
    path("logout/", logout_and_redirect_to_login, name='logout'),
]

words/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from words.views import (AddDictionaryView, AddPairWordView, ImportWordsView,
                         RepeatWordsView, ShowAllDictionaryUserView,
                         ShowDictionaryView, StudyWordsView,
                         UpdateDictionaryView, delete_dictionary, reset,
                         show_error_words)

app_name = 'words'

urlpatterns = [
    path('add-new-dictionary/', login_required(AddDictionaryView.as_view()), name='add_dictionary'),
    path('add-new-words/', login_required(AddPairWordView.as_view()), name='add_new_words'),
    path('import-new-words/', login_required(ImportWordsView.as_view()), name='import_new_words'),

    path('', ShowAllDictionaryUserView.as_view(), name='show_dictionaries'),
    path('show-dictionary/<slug:dict_slug>', ShowDictionaryView.as_view(), name='show_dictionary'),
    path('update-dictionary/<slug:dict_slug>', UpdateDictionaryView.as_view(), name='update_dictionary'),
    path('delete-dictionary/<slug:dict_slug>', delete_dictionary, name='delete_dictionary'),

    path('study-words/<slug:dict_slug>', StudyWordsView.as_view(), name='study_words'),
    path('repeat-words/<slug:dict_slug>', RepeatWordsView.as_view(), name='repeat_words'),

    path('congratulations/', reset, name='congratulations'),
    path('error-words/', show_error_words, name='error_words'),
]

words/forms.py
from django import forms

from .models import Dictionary, PairWord


class AddDictionaryForm(forms.ModelForm):
    title = forms.CharField(max_length=150,
                            widget=forms.TextInput(attrs={'placeholder': 'Enter the name of the dictionary',
                                                          'style': 'width: 300px;'}))

    class Meta:
        model = Dictionary
        fields = ('title',)


class AddPairWordForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dictionary'].empty_label = 'No dictionary selected'
        self.fields['dictionary'].queryset = Dictionary.objects.filter(user=user)

    original_word = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'original word', 'class': 'input-word'}))

    translation_word = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'translation word', 'class': 'input-word'}))

    class Meta:
        model = PairWord
        fields = ('original_word', 'translation_word', 'dictionary')


class ImportWordsForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dictionary'].empty_label = 'No dictionary selected'
        self.fields['dictionary'].queryset = Dictionary.objects.filter(user=user)

    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Original 1 - Translation 1\n'
                                                                       'Original 2 - Translation 2\n'
                                                                       'Original 3 - Translation 3\n'
                                                                       '...'
                                                        }))

    sep_choice = forms.ChoiceField(
        choices=((' - ', 'Default: - '), ('Custom', 'Custom separator')),
        initial=' - ',
        widget=forms.RadioSelect(),
    )
    custom_sep = forms.CharField(
        max_length=10,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Enter custom separator'}),
    )

    class Meta:
        model = PairWord
        fields = ('dictionary', 'text', 'sep_choice', 'custom_sep')


class RepeatWordForm(forms.Form):
    user_answer = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'user-answer',
                'autofocus': True,
                'placeholder': 'Enter your answer...',
            }),
        label='your answer',
        max_length=100
    )


class PairWordForm(forms.ModelForm):
    original = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'word'}),
        required=True
    )

    translation = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'word'}),
        required=True
    )

    delete = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'delete-checkbox'})
    )

    class Meta:
        model = PairWord
        fields = ['original', 'translation']

words/views.py
from random import shuffle

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from common.views import DataMixin

from .forms import (AddDictionaryForm, AddPairWordForm, ImportWordsForm,
                    PairWordForm, RepeatWordForm)
from .models import Dictionary, PairWord, UserLearningData
from .utils import (Slug, get_delete_and_updated_words, get_existing_originals,
                    get_sep, get_unique_pairs)


class AddDictionaryView(DataMixin, SuccessMessageMixin, CreateView):
    form_class = AddDictionaryForm
    template_name = 'words/add_dictionary.html'
    title = "New Dictionary"

    def form_valid(self, form):
        user = self.request.user

        slug = Slug(form.cleaned_data['title']).slug
        existing_dictionary = Dictionary.objects.filter(user=user, slug=slug).first()
        if existing_dictionary:
            messages.error(self.request, 'Dictionary with this name already exists.')
            return redirect(reverse('words:add_dictionary'))

        dictionary = form.save(commit=False)
        dictionary.user = user

        dictionary.save()

        return HttpResponseRedirect(reverse('words:add_new_words'))


class AddPairWordView(DataMixin, CreateView):
    form_class = AddPairWordForm
    template_name = 'words/add_new_pair_words.html'
    title = 'Add New Pairs Words'

    def form_valid(self, form):
        dictionary_id = form.data.get('dictionary')
        dictionary = Dictionary.objects.get(id=dictionary_id)

        original_words = form.data.getlist('original_word')
        translation_words = form.data.getlist('translation_word')

        pair_objects = []
        for original, translation in zip(original_words, translation_words):
            original, translation = original.strip().lower(), translation.strip().lower()
            pair_objects.append(PairWord(original=original, translation=translation, dictionary=dictionary))

        PairWord.objects.bulk_create(pair_objects)
        dictionary.save()

        return HttpResponseRedirect(reverse('words:show_dictionary', kwargs={'dict_slug': dictionary.slug}))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs


class ImportWordsView(DataMixin, CreateView):
    form_class = ImportWordsForm
    template_name = 'words/import_words.html'
    title = 'Import New Pairs Words'

    def form_valid(self, form):
        id_dictionary = form.data.get('dictionary')
        dictionary = Dictionary.objects.get(id=id_dictionary)

        text = form.cleaned_data.get('text')

        if text:
            sep = get_sep(form)
            db_words = PairWord.objects.filter(dictionary_id=id_dictionary)
            existing_originals = get_existing_originals(db_words)
            words_for_db = get_unique_pairs(text, existing_originals, sep, dictionary, PairWord)

            if words_for_db:
                PairWord.objects.bulk_create(words_for_db)
                dictionary.save()

        return HttpResponseRedirect(reverse('words:show_dictionary', kwargs={'dict_slug': dictionary.slug}))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs


class ShowAllDictionaryUserView(DataMixin, ListView):
    model = Dictionary
    template_name = 'words/show_all_dictionaries_user.html'
    title = 'Home'

    def get_queryset(self):
        dictionaries = Dictionary.objects.filter(user_id=self.request.user.pk).order_by('-updated_at')
        dictionaries = dictionaries.annotate(count_words=Count('pairword'))
        return dictionaries


class ShowDictionaryView(DetailView):
    model = Dictionary
    template_name = 'words/show_dictionary.html'
    slug_url_kwarg = 'dict_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dict_slug'] = self.kwargs['dict_slug']
        context['title'] = self.object.title
        word_list = PairWord.objects.filter(dictionary=self.object).select_related('dictionary').order_by('-id')

        context['word_list'] = word_list
        context['word_data'] = [{'original': word.original, 'translation': word.translation} for word in word_list]
        return context

    def get_queryset(self):
        dictionary = Dictionary.objects.filter(user_id=self.request.user.pk, slug=self.kwargs[self.slug_url_kwarg])
        dictionary = dictionary.annotate(count_words=Count('pairword'))

        return dictionary


class UpdateDictionaryView(SuccessMessageMixin, UpdateView):
    model = Dictionary
    template_name = 'words/update_dictionary.html'
    slug_url_kwarg = 'dict_slug'
    context_object_name = 'dictionary'
    fields = ['title']

    def get_queryset(self):
        return Dictionary.objects.filter(slug=self.kwargs['dict_slug'], user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dictionary = self.object
        words_to_change = PairWord.objects.filter(dictionary=dictionary).order_by('-id')
        context['title'] = dictionary.title
        context['count_words'] = words_to_change.count()
        PairWordFormSet = inlineformset_factory(Dictionary, PairWord, form=PairWordForm, extra=0)
        context['formset'] = PairWordFormSet(instance=dictionary, queryset=words_to_change)

        return context

    def post(self, request, *args, **kwargs):
        changed_title = self.request.POST.get('title').strip()
        slug = Slug(changed_title).slug

        dictionary = self.get_object()
        words_to_change = PairWord.objects.filter(dictionary=dictionary)
        PairWordFormSet = inlineformset_factory(Dictionary, PairWord, form=PairWordForm, extra=0)
        formset = PairWordFormSet(request.POST, instance=dictionary, queryset=words_to_change)

        if formset.is_valid():
            words_to_delete, updated_words = get_delete_and_updated_words(formset, PairWord, dictionary)

            if words_to_delete:
                # Выполняем удаление слов
                PairWord.objects.filter(id__in=words_to_delete).delete()

            if updated_words:
                PairWord.objects.bulk_update(updated_words, ['original', 'translation'])

            if kwargs['dict_slug'] != slug:
                dictionary.title = changed_title

            dictionary.save()
            messages.success(request, f'the {dictionary.title} has been changed')
        return redirect('words:update_dictionary', dict_slug=slug)


def delete_dictionary(request, dict_slug):
    dictionary = get_object_or_404(Dictionary, slug=dict_slug, user=request.user)
    if dictionary:
        dictionary.delete()

        return redirect('words:show_dictionaries')


class RepeatWordsView(SuccessMessageMixin, DetailView):
    model = Dictionary
    template_name = 'words/study_words.html'
    slug_url_kwarg = 'dict_slug'

    def get_context(self, **kwargs):
        title = ' '.join(kwargs["dict_slug"].split('-')).title()
        form = RepeatWordForm()
        reset_url = kwargs.get('reset_url')
        current_word_index = kwargs['request'].session.get('current_word_index') or 0
        custom_messages = {
            'translation': kwargs['translation'],
            'original': kwargs['original'],
        }

        if kwargs.get('user_answer'):
            custom_messages['error_answer'] = kwargs['user_answer'] != kwargs.get('original')
            custom_messages['user_answer'] = kwargs.get('user_answer')
            kwargs['request'].session['current_word_index'] = current_word_index + 1

            if kwargs['user_answer'] != kwargs.get('original'):
                error_words = kwargs['request'].session.get('error_words') or list()
                error_words.append((kwargs['original'], kwargs['translation']))
                kwargs['request'].session['error_words'] = error_words
        length = kwargs["request"].session.get("words")
        if length:
            length = len(length)
        context = {
            'title': f'Repeat {title} | {current_word_index + 1}/{length}',
            'form': form,
            'reset_url': reset_url,
            'custom_messages': custom_messages,
        }

        return context

    @staticmethod
    def check_dict_session(request, **kwargs):
        if kwargs['dict_slug'] != request.session.get('dict_session'):
            request.session['dict_session'] = kwargs['dict_slug']

    def get_pair(self, request, **kwargs):
        self.check_dict_session(request, **kwargs)

        words = request.session.get('words')
        current_word_index = request.session.get('current_word_index') or 0

        if words is None:
            request.session['error_words'] = None
            words = PairWord.objects.filter(dictionary__slug=kwargs['dict_slug'])
            words = [(pair.original, pair.translation) for pair in words]
            shuffle(words)

        if current_word_index < len(words) - 1:
            original = words[current_word_index][0]
            translation = words[current_word_index][1]
            request.session['words'] = words
            return original, translation

    def get(self, request, *args, **kwargs):
        pair = self.get_pair(request, **kwargs)

        if pair:
            context = self.get_context(
                **{
                    'request': request,
                    'dict_slug': kwargs["dict_slug"],
                    'translation': pair[1],
                    'original': pair[0],
                }
            )

templates/words/add_dictionary.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Add New Dictionary</h1>

        <form method="post">
            {% csrf_token %}
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "error" %}
                        <div class="error-message">{{ message }}</div>
                    {% endif %}
                {% endfor %}

            {% endif %}

            <div>
                <p>
                    {{ form.title }}
                </p>
            </div>
            <p>
                <button type="submit">Add Dictionary</button>
            </p>
        </form>
    </div>
{% endblock %}

templates/words/add_new_pair_words.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'my_project/css/dictionary_details.css' %}">
{% endblock %}


{% block content %}

    <div>
        <h1>Add New Words</h1>
        <div>
            <a href="{% url 'words:import_new_words' %}">
                <button type="submit">Import Words</button>
            </a>
        </div>
        <form method="post">
            {% csrf_token %}

            <div><p>{{ form.dictionary }}</p></div>

            <div class="words" id="word-fields">
                <!-- Первая пара полей -->
                <div class="word-pair">
                    <span class="word">{{ form.original_word }}</span>
                    <span class="separator"> | </span>
                    <span class="word">{{ form.translation_word }}</span>
                </div>

            </div>

            <div class="button-container">
                <button type="submit" id="add-word-button">Add more words</button>
                <button type="submit" class="green-button right-button">Save Dictionary</button>
            </div>

        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            var canAddField = true;  // Флаг, разрешающий добавление новых полей

            $("#add-word-button").click(function () {
                if (canAddField) {
                    var originalWord = $("input[name='original_word']").last();
                    var translationWord = $("input[name='translation_word']").last();

                    // Проверяем, что последние поля не пустые
                    if (originalWord.val() !== "" && translationWord.val() !== "") {
                        var newWordField = `
                        <div>
                            <div class="word-pair">
                                <span class="word">{{ form.original_word }}</span>
                                <span class="separator"> | </span>
                                <span class="word">{{ form.translation_word }}</span>
                            </div>
                            <button type="submit" class="remove-word-button red-button right-button">Remove</button>
                        </div>
                        `;
                        $("#word-fields").append(newWordField);

                        // Добавляем обработчик для кнопки "Remove"
                        $(".remove-word-button").last().click(function () {
                            $(this).parent().remove();
                        });
                    } else {
                        alert("Заполните предыдущую пару слов перед добавлением новой.");
                        canAddField = false;  // Запретить добавление новых полей
                    }
                }
            });

            // Вешаем обработчик на изменение текущих полей
            $(document).on("input", "input[name='original_word'], input[name='translation_word']", function () {
                canAddField = true;  // Разрешить добавление новых полей после заполнения текущих
            });
        });
    </script>
{% endblock %}

templates/words/error_words.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'my_project/css/dictionary_details.css' %}">
{% endblock %}

{% block content %}
    <h1>Error Words {{ error_words|length }}</h1>
    <div class="words">
        {% if error_words %}

            <ul>
                {% for original, translation in error_words %}
                    <li>
                        <div class="word-pair">
                            <span class="word">{{ original }}</span>
                            <span class="separator"> | </span>
                            <span class="word">{{ translation }}</span>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>You did a good job and you didn't make any mistakes! Keep it up!</p>
        {% endif %}
    </div>

{% endblock %}

templates/words/finished.html
{% extends 'base.html' %}

{% block content %}
    <h1>Congratulations you are completely finished dictionary!</h1>
    <p>
        <a href="{% url 'words:show_dictionaries' %}">
            <button type="submit">RESET</button>
        </a>

            <a href="{% url 'words:error_words' %}">
                <button type="button">LOOK ERRORS</button>
            </a>

    </p>
{% endblock %}

templates/words/import_words.html
{% extends 'base.html' %}

{% block content %}
    <div>
    <h1> Import Words</h1>
        <p>
            <a href="{% url 'words:add_new_words' %}">
                 <button type="submit" class="red-button">Cancel Import</button>
            </a>
        </p>
        <form method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            <div><p> Select Dictionary: {{ form.dictionary }}</p></div>

            <div><p>Import Words: {{ form.text }}</p></div>

            <div>Separator: {{ form.sep_choice }} <p>{{ form.custom_sep }}</p> </div>

            <button type="submit" class="green-button">Import Words</button>

        </form>

    </div>
{% endblock %}

templates/words/repeat_words.html
{% extends 'base.html' %}


{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="error_message"> {{ message }} </div>
            {% else %}
                <div class="success_message"> {{ message }} </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <p>{{ form.user_answer.label_tag }} {{ translation }}</p>
        {{ form.user_answer }}
        <p>
            <button type="submit">Send</button>
            <a href="{% url 'words:repeat_words' slug %}">
                <button type="button">RESET</button>
            </a>
        </p>


    </form>


{% endblock %}

templates/words/show_all_dictionaries_user.html
{% extends 'base.html' %}
{% load  static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'my_project/css/dictionary_details.css' %}">
{% endblock %}

{% block content %}

    {% if dictionary_list %}

        <h1>Your Dictionaries {% if dictionary_list %}| {{ dictionary_list|length }} {% endif %} </h1>

        <div class="card-group">
            {% for dictionary in dictionary_list %}
                {% if dictionary.count_words %}
                    <div class="card">
                        <div class="card-top">
                            <small class="text-left text-body-secondary">Created: {{ dictionary.created_at }} </small>
                            <small class="text-right text-body-secondary">Last
                                updated: {{ dictionary.updated_at }}</small>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ dictionary.title }}</h5>
                            <div class="ml-auto">
                                <a href="{{ dictionary.get_absolute_url }}" class="btn btn-primary">
                                    <button type="button">Show Dictionary</button>
                                </a>
                            </div>
                            <p class="card-text-bottom">Words: {{ dictionary.count_words }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    {% else %}

        <h1>You don't have dictionaries yet</h1>

        {% if request.user.is_authenticated %}
            <a href="{% url 'words:add_dictionary' %}" class="btn btn-success">
                <button>Create Dictionary</button>
            </a>
        {% endif %}

    {% endif %}

{% endblock %}

templates/words/show_dictionary.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'my_project/css/dictionary_details.css' %}">
    <link rel="stylesheet" href="{% static 'my_project/css/words_cards.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}

    <h1>{{ dictionary.title }} | total words: {{ dictionary.count_words }}</h1>

    <div class="time-created">
        <span>Created: {{ dictionary.created_at|date:"Y-m-d H:i" }}</span>

        <div class="centered-image">
            {% if dictionary.image %}
                <img src="{{ object.image.url }}" alt="dictionary image">
            {% else %}
                <img src="{% static 'my_project/dictionary/img/words_header.png' %}" alt="dictionary image">
            {% endif %}
        </div>

        <span>Updated: {{ dictionary.updated_at|date:"Y-m-d H:i" }}</span>
    </div>

        <div>
            {% include 'inc/words_cards.html' %}
        </div>

    <div class="button-container">
        <a href="{% url 'words:repeat_words' dictionary.slug %}">
            <button type="button">Repeat Dictionary</button>
        </a>

        <a href="{% url 'words:study_words' dictionary.slug %}">
            <button type="button">Study Dictionary</button>
        </a>

        <a href="{% url 'words:update_dictionary' dictionary.slug %}">
            <button type="button">Change Dictionary</button>
        </a>

        <a href="{% url 'words:add_new_words' %}">
            <button type="button">Add New Pair</button>
        </a>

        <a href="{% url 'words:delete_dictionary' dict_slug %}">
            <button type="button" class="red-button">Delete Dictionary</button>
        </a>
    </div>

    <div class="words">
        <ul>
            {% for pair in word_list %}
                <li>
                    <div class="word-pair">
                        <span class="number"> {{ forloop.counter }}</span>
                        <span class="word">{{ pair.original }}</span>
                        <span class="separator"> | </span>
                        <span class="word">{{ pair.translation }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/words/study_words.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title-color">{{ title }}</h1>

    <div class="content-box">

        <form method="post">
            {% csrf_token %}

            <div class="translation-box">
                <h3>
                    <span class="color-translation-title">Enter translation for:</span>
                    {{ custom_messages.translation }}
                </h3>
            </div>
            <br>
            <div class="user-container">
                <div class="label-box">
                    <span class="color-translation-title">{{ form.user_answer.label_tag }} </span>
                    <p>{{ form.user_answer }}</p>
                </div>

                <div class="button-answer">
                    <a href="{{ user_answer_url }}">
                        <button type="submit">Answer</button>
                    </a>
                </div>
            </div>
            <div class="button-reset">
                <a href="{{ reset_url }}">
                    <button type="button" class="red-button">RESET</button>
                </a>
            </div>
        </form>
    </div>


    <script>
        // отключение автозаполнения при вводе
        document.getElementById("id_user_answer").setAttribute("autocomplete", "off");
    </script>
{% endblock %}

templates/words/update_dictionary.html
{% extends 'base.html' %}
{% load  static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'my_project/css/dictionary_details.css' %}">
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}

        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <h3 class="success-message text-center"> {{ message }}</h3>
                {% endif %}
            {% endfor %}
        {% endif %}

        <h1>Edit Dictionary:
            <input type="text" class="word" name="title" value="{{ dictionary.title }}">
        </h1>

        <p class="button-along-edges">
            <a href="{% url 'words:show_dictionary' dict_slug=dictionary.slug %}">
                <button type="button">Back to Dictionary</button>
            </a>

            <button type="submit" class="green-button">Save Changes</button>
        </p>

        {% for form in formset %}
            <div class="word-pair">
                <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}">
                <input type="text" class="word" name="{{ form.prefix }}-original" value="{{ form.instance.original }}"
                       required>
                <span class="separator"> | </span>
                <input type="text" class="word" name="{{ form.prefix }}-translation"
                       value="{{ form.instance.translation }}" required>
                <!-- Добавляем поле delete для каждой формы -->
                <input type="checkbox" name="{{ form.prefix }}-delete" id="{{ form.prefix }}-delete">
            </div>
        {% endfor %}

        <p class="button-along-edges">
            <a href="{% url 'words:show_dictionary' dict_slug=dictionary.slug %}">
                <button type="button">Back to Dictionary</button>
            </a>

            <button type="submit" class="green-button">Save Changes</button>
        </p>

    </form>

{% endblock %}

templates/words/user_answer.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title-color"> {{ title }} </h1>

    <div class="content-box">
        <div>
            {% if custom_messages %}

                {% if custom_messages.translation %}
                    <h3>
                        {% if not custom_messages.error_answer %}
                            <span class="color-translation-title">You are right!</span>
                        {% else %}
                            correct answer for "{{ custom_messages.translation }}":
                        {% endif %}
                    </h3>
                    <div class="correct-answer">
                        <input type="text" value="{{ custom_messages.original }}" class="success-answer" readonly>
                    </div>

                {% endif %}

                <h3>{{ custom_messages.point }}</h3>
                <div class="error-container">
                    {% if custom_messages.error_answer %}
                        <h3>Oops..wrong.</h3>
                        <input type="text" value="{{ custom_messages.user_answer }}" class="error-answer" readonly>
                    {% endif %}
                </div>
            {% endif %}
            <p class="button-continue">
                <a href="{{ come_back_url }}">
                    <button type="button" autofocus>CONTINUE</button>
                </a>
            </p>

        </div>
    </div>

{% endblock %}