assistant_in_learning_new_words/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include("debug_toolbar.urls")),

    path('users/', include("users.urls", namespace="users")),
    path('', include("words.urls", namespace="words")),
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (LogInView, SignUpView, UserUpdateView,
                    logout_and_redirect_to_login)

app_name = 'users'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup'),
    path("login/", LogInView.as_view(), name='login'),
    path("profile/<int:pk>", login_required(UserUpdateView.as_view()), name='profile'),
    path("logout/", logout_and_redirect_to_login, name='logout'),
]

words/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from words.views import (AddDictionaryView, AddPairWordView, ImportWordsView,
                         RepeatWordsView, ShowAllDictionaryUserView,
                         ShowDictionaryView, StudyWordsView,
                         UpdateDictionaryView, delete_dictionary, reset,
                         show_error_words)

app_name = 'words'

urlpatterns = [
    path('add-new-dictionary/', login_required(AddDictionaryView.as_view()), name='add_dictionary'),
    path('add-new-words/', login_required(AddPairWordView.as_view()), name='add_new_words'),
    path('import-new-words/', login_required(ImportWordsView.as_view()), name='import_new_words'),

    path('', ShowAllDictionaryUserView.as_view(), name='show_dictionaries'),
    path('show-dictionary/<slug:dict_slug>', ShowDictionaryView.as_view(), name='show_dictionary'),
    path('update-dictionary/<slug:dict_slug>', UpdateDictionaryView.as_view(), name='update_dictionary'),
    path('delete-dictionary/<slug:dict_slug>', delete_dictionary, name='delete_dictionary'),

    path('study-words/<slug:dict_slug>', StudyWordsView.as_view(), name='study_words'),
    path('repeat-words/<slug:dict_slug>', RepeatWordsView.as_view(), name='repeat_words'),

    path('congratulations/', reset, name='congratulations'),
    path('error-words/', show_error_words, name='error_words'),
]

templates/inc/_nav.html
<div class="menu-wrapper">
    <ul class="menu">
        <li><a href="{% url 'words:show_dictionaries' %}">Home</a></li>

        {% if request.user.is_authenticated %}

            <li class="dropdown">
                <a href="#">Create</a>
                <ul class="dropdown-content">
                    <li><a href="{% url 'words:add_dictionary' %}">New Dictionary</a></li>
                    <li><a href="{% url 'words:add_new_words' %}">New Words</a></li>
                </ul>
            </li>

            <li class="right-align">
                <a href="{% url 'users:profile' user.id %}">{{ user.username }}</a>
                |
                <a href="{% url 'users:logout' %}">Logout</a>
            </li>

            {% if request.user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">
                    <button>AdminSite</button>
                </a></li>
            {% endif %}

        {% else %}
            <li class="right-align">
                <a href="{% url 'users:signup' %}">Sign Up</a> | <a href="{% url 'users:login' %}">Log In</a>
            </li>
        {% endif %}


    </ul>
</div>

templates/inc/words_cards.html
<div class="container">
    <div class="card" id="card">
        <div class="front">
            <div class="original center">
                <h1>{{ word.original }}</h1>
            </div>
        </div>
        <div class="back">
            <div class="translation center">
                <h1>{{ word.translation }}</h1>
            </div>
        </div>
    </div>

    <div class="buttons-card">
        <button id="prevBtn" class="button-previous">
            <i class="fa fa-arrow-left"></i>
        </button>
        <div id="wordCount" class="count-words">0/0</div>
        <button id="nextBtn" class="button-next">
            <i class="fa fa-arrow-right"></i>
        </button>
    </div>
</div>

<script>
    const card = document.getElementById('card');
    const prevBtn = document.getElementById('prevBtn');
    const nextBtn = document.getElementById('nextBtn');
    const wordList = {{ word_data|safe }};
    const wordCountElement = document.getElementById('wordCount');
    const totalWords = wordList.length; // Общее количество слов
    let currentIndex = 0;
    let isFlipped = false;

    function showCard(index) {
        const word = wordList[index];
        document.querySelector('.original h1').textContent = word.original;
        document.querySelector('.translation h1').textContent = word.translation;
        isFlipped = false;
        card.classList.remove('is-flipped');

        const currentIndexDisplay = index + 1;
        wordCountElement.textContent = `${currentIndexDisplay}/${totalWords}`;

        // Проверка, можно ли нажать кнопку "Previous" и "Next"
        if (currentIndex === 0) {
            prevBtn.classList.add('button-disabled');
        } else {
            prevBtn.classList.remove('button-disabled');
        }
        if (currentIndex === wordList.length - 1) {
            nextBtn.classList.add('button-disabled');
        } else {
            nextBtn.classList.remove('button-disabled');
        }
    }

    prevBtn.addEventListener('click', function () {
        if (currentIndex > 0) {
            currentIndex--;
            showCard(currentIndex);
        }
    });

    nextBtn.addEventListener('click', function () {
        if (currentIndex < wordList.length - 1) {
            currentIndex++;
            showCard(currentIndex);
        }
    });

    showCard(currentIndex);

    card.addEventListener('click', function () {
        if (isFlipped) {
            document.querySelector('.original h1').textContent = wordList[currentIndex].original;
        } else {
            document.querySelector('.translation h1').textContent = wordList[currentIndex].translation;
        }
        isFlipped = !isFlipped;
        card.classList.toggle('is-flipped');
    });
</script>
{#    <div id="wordData" data-word_data="{{ word_data|escapejs|safe }}"></div>#}
{#    <script src="{% static 'my_project/js/words_cards.js' %}"></script>#}